apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "irmf-backend.fullname" . }}-config
  labels:
    {{- include "irmf-backend.labels" . | nindent 4 }}
data:
  PUBLIC_HOSTNAME: {{ .Values.publicHostname | quote }}
