apiVersion: v1
kind: Secret
metadata:
  name: {{ include "irmf-backend.fullname" . }}-mailgun-secret
  labels:
    {{- include "irmf-backend.labels" . | nindent 4 }}
type: Opaque
data:
  MAILGUN_DOMAIN: {{ .Values.mailgun.domain | b64enc }}
  MAILGUN_API_KEY: {{ .Values.mailgun.apiKey | b64enc }}
  MAILGUN_SENDER_EMAIL: {{ .Values.mailgun.senderEmail | b64enc }}
