apiVersion: v1
kind: Service
metadata:
  name: {{ include "irmf-backend.fullname" . }}
  labels:
    {{- include "irmf-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "irmf-backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irmf-frontend.fullname" . }}
  labels:
    {{- include "irmf-frontend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "irmf-frontend.selectorLabels" . | nindent 4 }}