replicaCount: 1

backendImage:
  repository: ghcr.io/vaclove/irmf/backend
  pullPolicy: Always
  tag: "latest"

frontendImage:
  repository: ghcr.io/vaclove/irmf/frontend
  pullPolicy: Always
  tag: "latest"

backendService:
  type: ClusterIP
  port: 3000

frontendService:
  type: ClusterIP
  port: 3000 # Next.js default port

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: guests.irmf.cz
      paths:
        - path: /api
          pathType: ImplementationSpecific
        - path: /
          pathType: ImplementationSpecific
  tls: []

publicHostname: "https://guests.irmf.cz"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
