name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  BACKEND_APP_NAME: irmf-backend
  FRONTEND_APP_NAME: irmf-frontend
  ACR_NAME: irmfcz.azurecr.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}/backend:latest,${{ env.ACR_NAME }}/backend:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ env.ACR_NAME }}/frontend:latest,${{ env.ACR_NAME }}/frontend:${{ github.sha }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    outputs:
      backend_url: ${{ steps.deploy.outputs.fqdn }}
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure Container App
        id: deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          environment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ env.BACKEND_APP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}/backend:${{ github.sha }}
          registryUrl: ${{ env.ACR_NAME }}
          registryUsername: ${{ secrets.AZURE_CLIENT_ID }}
          registryPassword: ${{ secrets.AZURE_CLIENT_SECRET }}
          targetPort: 3000
          ingress: internal
          environmentVariables: |
            PUBLIC_HOSTNAME=https://my.irmf.cz
          secrets: |
            mailgun-api-key=${{ secrets.MAILGUN_API_KEY }}
            mailgun-domain=${{ secrets.MAILGUN_DOMAIN }}
            mailgun-sender-email=${{ secrets.MAILGUN_SENDER_EMAIL }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend, deploy-backend]
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          environment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ env.FRONTEND_APP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}/frontend:${{ github.sha }}
          registryUrl: ${{ env.ACR_NAME }}
          registryUsername: ${{ secrets.AZURE_CLIENT_ID }}
          registryPassword: ${{ secrets.AZURE_CLIENT_SECRET }}
          targetPort: 3000
          ingress: external
          customDomainHostName: my.irmf.cz
          environmentVariables: |
            NEXT_PUBLIC_API_URL=https://${{ needs.deploy-backend.outputs.backend_url }}
