name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  BACKEND_APP_NAME: irmf-backend
  FRONTEND_APP_NAME: irmf-frontend
  ACR_NAME: irmfcz.azurecr.io

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.deploy.outputs.fqdn }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure Container App
        id: deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          environment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ env.BACKEND_APP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}/backend:${{ github.sha }}
          targetPort: 3000
          ingress: internal
          environmentVariables:
            - name: PUBLIC_HOSTNAME
              value: "https://my.irmf.cz"
          secrets:
            - name: mailgun-api-key
              value: ${{ secrets.MAILGUN_API_KEY }}
            - name: mailgun-domain
              value: ${{ secrets.MAILGUN_DOMAIN }}
            - name: mailgun-sender-email
              value: ${{ secrets.MAILGUN_SENDER_EMAIL }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          environment: ${{ secrets.CONTAINER_APP_ENVIRONMENT }}
          containerAppName: ${{ env.FRONTEND_APP_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}/frontend:${{ github.sha }}
          targetPort: 3000
          ingress: external
          customDomainHostName: my.irmf.cz
          environmentVariables:
            - name: NEXT_PUBLIC_API_URL
              value: "https://${{ needs.deploy-backend.outputs.backend_url }}"
